---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1x6xk6up63dcnnp06lw2nsvhshdv2ppktnlfjf7unepvg3zzzh4cs2yh98t"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1x6xk6up63dcnnp06lw2nsvhshdv2ppktnlfjf7unepvg3zzzh4cs2yh98t"
stores:
  yaml:
    indent: 2
