apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Nq+rnlqDLD1mpqg=,iv:kBJ6EV1sPeAEqF6pu65+uT4QnlOSnyQP0d1BQTGHghA=,tag:B68X91M7yc5YVjFdu0UM+w==,type:str]
sops:
  age:
    - recipient: age1x6xk6up63dcnnp06lw2nsvhshdv2ppktnlfjf7unepvg3zzzh4cs2yh98t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TTFGR2lINU1kR2pUZUlt
        Ry96VnBJVDcvcjkvMGJTN2o4VkFlYU5YdkRNClRJNk94aVdjck1TbG5LNmtZQ1pq
        eFFTbE85WGIraWxONFJLTkR2SmoxOUUKLS0tIFozcmZPR2I4cVRnNTdjbFVpWUJN
        cjdzODl6cHpXSU5aZTUyWXNrT0FvNzAKU2gKrbQb2kgwoFExnQS8PmtkMtFNSsn/
        VTV8LhHe/rS+aCpgo/1s8quNW9yLmc8xMMUPId/dut9gobW0g45qbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T05:38:42Z"
  mac: ENC[AES256_GCM,data:blY4Bqkhmi/s2FHN5i3PJ2uYJwqV8mtyq2zOP/j4A39sfbykm5COTgTamwD7mwYiVavquQBJsb2nYZ4yECcz3ogjfNsJicsjShvGC3iM7gCtMyHDwpJxOzCFxyoagVDV+g1Ozo17/pBcUOJ65YNi9ykQrPoYB6VMK0tT6O4nhxc=,iv:XmnMjGN0x7kNk5vmPxfkkF9fmxG4iP0tj/z6yBEO/as=,tag:aDaj5JekWJlY5fRUU6X/mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
